### ISSUE TITLE
Why scale factor is 12 in testing but 1 in training?

### ISSUE THREAD

**Issue by ShenZheng2000** [Li-Chongyi/Zero-DCE_extension#5]
Hello, authors. Thanks for your excellent work. 
I notice that line 20 of lowlight_test.py defines the scale factor as 12, whereas line 105 of lowlight_train.py assumes that the default scale factor is 1. 
I would like to know (1) the reason for this inconsistency (2) which one I should adopt for training the model.
Thanks!

**Comment by Li-Chongyi** [comment]
> Hello, authors. Thanks for your excellent work.
> I notice that line 20 of lowlight_test.py defines the scale factor as 12, whereas line 105 of lowlight_train.py assumes that the default scale factor is 1.
> I would like to know (1) the reason for this inconsistency (2) which one I should adopt for training the model.
> Thanks!

Hi,

We used the images of full resolution to train the model, without downsampling operations. But, our curve-based method can achieve acceleration by downsampling the input (scale 12). It means that we can use low-resolution images to compute the curve parameters and upsample the parameter maps back to the original resolution to implement the curve map in the testing phase.

**Comment by ShenZheng2000** [comment]
Thanks for your clarification!
